platform :ios, '10.0'
use_frameworks!

flutter_application_path = '../BasicAppFlutter'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'BasicAppSwift' do
  
  install_all_flutter_pods(flutter_application_path)

end

